import type { UnparsedSpell } from "@/components/spells/spellData/spells.types";

export const playerHandbookSpells: readonly UnparsedSpell[] = [
	{
		id: 2_618_831,
		name: "Arcane Vigor",
		level: 2,
		castingTime: "Bonus Action",
		range: "Self",
		components: "VS",
		duration: "Instant",
		school: "Abjuration",
		description:
			"<p>You tap into your life force to heal yourself. Roll one or two of your unexpended Hit Point Dice, and regain a number of Hit Points equal to the roll’s total plus your spellcasting ability modifier. Those dice are then expended.</p>",
		onHigherLevels:
			"The number of unexpended Hit Dice you can roll increases by one for each spell slot level above 2.",
		classes: ["Sorcerer", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_834,
		name: "Elementalism",
		level: 0,
		castingTime: "Action",
		range: { value: 30, unit: "ft" },
		aoeRange: "30 ft (5 ft □)",
		components: "VS",
		duration: "Instant",
		school: "Transmutation",
		description:
			"<p>You exert control over the elements, creating one of the following effects within range.</p><p><em><strong>Beckon Air.</strong></em> You create a breeze strong enough to ripple cloth, stir dust, rustle leaves, and close open doors and shutters, all in a 5-foot Cube. Doors and shutters being held open by someone or something aren’t affected.</p><p><em><strong>Beckon Earth.</strong></em> You create a thin shroud of dust or sand that covers surfaces in a 5-foot-square area, or you cause a single word to appear in your handwriting in a patch of dirt or sand.</p><p><em><strong>Beckon Fire.</strong></em> You create a thin cloud of harmless embers and colored, scented smoke in a 5-foot Cube. You choose the color and scent, and the embers can light candles, torches, or lamps in that area. The smoke’s scent lingers for 1 minute.</p><p><em><strong>Beckon Water.</strong></em> You create a spray of cool mist that lightly dampens creatures and objects in a 5-foot Cube. Alternatively, you create 1 cup of clean water either in an open container or on a surface, and the water evaporates in 1 minute.</p><p><em><strong>Sculpt Element.</strong></em> You cause dirt, sand, fire, smoke, mist, or water that can fit in a 1-foot Cube to assume a crude shape (such as that of a creature) for 1 hour.</p>",
		classes: ["Druid", "Sorcerer", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_835,
		name: "Fount of Moonlight",
		level: 4,
		castingTime: "Action",
		range: "Self",
		components: "VS",
		concentration: true,
		duration: { value: 10, unit: "minute" },
		school: "Evocation",
		save: "Constitution",
		damage: { value: "2d6", type: ["Radiant"] },
		description:
			"<p>A cool light wreathes your body for the duration, emitting Bright Light in a 20-foot radius and Dim Light for an additional 20 feet.</p><p>Until the spell ends, you have Resistance to Radiant damage, and your melee attacks deal an extra 2d6 Radiant damage on a hit.</p><p>In addition, immediately after you take damage from a creature you can see within 60 feet of yourself, you can take a Reaction to force the creature to make a Constitution saving throw. On a failed save, the creature has the Blinded condition until the end of your next turn.</p>",
		classes: ["Bard", "Druid"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_836,
		name: "Jallarzi's Storm of Radiance",
		level: 5,
		castingTime: "Action",
		range: { value: 120, unit: "ft" },
		aoeRange: "120 ft (10 ft ○)",
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Evocation",
		save: "Constitution",
		damage: {
			value: "4d10",
			type: ["Radiant", "Thunder"],
		},
		description:
			"<p>You unleash a storm of flashing light and raging thunder in a 10-foot-radius, 40-foot-high Cylinder centered on a point you can see within range. While in this area, creatures have the Blinded and Deafened conditions, and they can’t cast spells with a Verbal component.</p><p>When the storm appears, each creature in it makes a Constitution saving throw, taking 2d10 Radiant damage and 2d10 Thunder damage on a failed save or half as much damage on a successful one. A creature also makes this save when it enters the spell’s area for the first time on a turn or ends its turn there. A creature makes this save only once per turn.</p>",
		onHigherLevels:
			"The Radiant and Thunder damage increase by 1d10 for each spell slot level above 5.",
		classes: ["Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "pinch of phosphorus",
	},
	{
		id: 2_618_837,
		name: "Power Word Fortify",
		level: 7,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		components: "V",
		duration: "Instant",
		school: "Enchantment",
		tags: ["Buff"],
		description:
			"<p>You fortify up to six creatures you can see within range. The spell bestows 120 Temporary Hit Points, which you divide among the spell’s recipients.</p>",
		classes: ["Bard", "Cleric"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_841,
		name: "Tasha's Bubbling Cauldron",
		level: 6,
		castingTime: "Action",
		range: { value: 5, unit: "ft" },
		components: "VSM",
		duration: { value: 10, unit: "minute" },
		school: "Conjuration",
		description:
			"<p>You conjure a claw-footed cauldron filled with bubbling liquid. The cauldron appears in an unoccupied space on the ground within 5 feet of you and lasts for the duration. The cauldron can’t be moved and disappears when the spell ends, along with the bubbling liquid inside it.</p><p>The liquid in the cauldron duplicates the properties of a Common or an Uncommon potion of your choice (such as a Potion of Healing). As a Bonus Action, you or an ally can reach into the cauldron and withdraw one potion of that kind. The potion is contained in a vial that disappears when the potion is consumed. The cauldron can produce a number of these potions equal to your spellcasting ability modifier (minimum 1). When the last of these potions is withdrawn from the cauldron, the cauldron disappears, and the spell ends.</p><p>Potions obtained from the cauldron that aren’t consumed disappear when you cast this spell again.</p>",
		classes: ["Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "gilded ladle worth 500+ GP",
	},
	{
		id: 2_618_842,
		name: "Yolande's Regal Presence",
		level: 5,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (10 ft ○)",
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Enchantment",
		save: "Wisdom",
		damage: {
			value: "4d6",
			type: ["Psychic"],
		},
		description:
			"<p>You surround yourself with unearthly majesty in a 10-foot Emanation. Whenever the Emanation enters the space of a creature you can see and whenever a creature you can see enters the Emanation or ends its turn there, you can force that creature to make a Wisdom saving throw. On a failed save, the target takes 4d6 Psychic damage and has the Prone condition, and you can push it up to 10 feet away. On a successful save, the target takes half as much damage only. A creature makes this save only once per turn.</p>",
		classes: ["Paladin", "Bard", "Wizard"],
		source: "Player’s Handbook",
		material: "miniature tiara",
	},
	{
		id: 2_618_854,
		name: "Phantasmal Force",
		level: 2,
		concentration: true,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		aoeRange: "60 ft (10 ft □)",
		components: "VSM",
		duration: { value: 1, unit: "minute" },
		school: "Illusion",
		save: "Intelligence",
		damage: {
			value: "2d8",
			type: ["Psychic"],
		},
		description:
			"<p>You attempt to craft an illusion in the mind of a creature you can see within range. The target makes an Intelligence saving throw. On a failed save, you create a phantasmal object, creature, or other phenomenon that is no larger than a 10-foot Cube and that is perceivable only to the target for the duration. The phantasm includes sound, temperature, and other stimuli.</p><p>The target can take a Study action to examine the phantasm with an Intelligence (Investigation) check against your spell save DC. If the check succeeds, the target realizes that the phantasm is an illusion, and the spell ends.</p><p>While affected by the spell, the target treats the phantasm as if it were real and rationalizes any illogical outcomes from interacting with it. For example, if the target steps through a phantasmal bridge and survives the fall, it believes the bridge exists and something else caused it to fall.</p><p>An affected target can even take damage from the illusion if the phantasm represents a dangerous creature or hazard. On each of your turns, such a phantasm can deal 2d8 Psychic damage to the target if it is in the phantasm’s area or within 5 feet of the phantasm. The target perceives the damage as a type appropriate to the illusion.</p>",
		classes: ["Warlock", "Bard", "Sorcerer", "Wizard"],
		material: "bit of fleece",
		source: "Player’s Handbook",
	},
	{
		id: 2_618_865,
		name: "Arcane Gate",
		level: 6,
		castingTime: "Action",
		range: { value: 500, unit: "ft" },
		components: "VS",
		concentration: true,
		duration: { value: 10, unit: "minute" },
		school: "Conjuration",
		description:
			"<p>You create linked teleportation portals. Choose two Large, unoccupied spaces on the ground that you can see, one space within range and the other one within 10 feet of you. A circular portal opens in each of those spaces and remains for the duration.</p><p>The portals are two-dimensional glowing rings filled with mist that blocks sight. They hover inches from the ground and are perpendicular to it.</p><p>A portal is open on only one side (you choose which). Anything entering the open side of a portal exits from the open side of the other portal as if the two were adjacent to each other. As a Bonus Action, you can change the facing of the open sides.</p>",
		tags: ["Teleportation"],
		classes: ["Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_870,
		name: "Armor of Agathys",
		level: 1,
		castingTime: "Bonus Action",
		range: "Self",
		components: "VSM",
		duration: { value: 1, unit: "hour" },
		school: "Abjuration",
		damage: {
			value: 5,
			type: ["Cold"],
		},
		description:
			"<p>Protective magical frost surrounds you. You gain 5 Temporary Hit Points. If a creature hits you with a melee attack roll before the spell ends, the creature takes 5 Cold damage. The spell ends early if you have no Temporary Hit Points.</p>",
		onHigherLevels:
			"The Temporary Hit Points and the Cold damage both increase by 5 for each spell slot level above 1.",
		tags: ["Buff"],
		classes: ["Paladin", "Warlock"],
		source: "Player’s Handbook",
		material: "shard of blue glass",
	},
	{
		id: 2_618_871,
		name: "Arms of Hadar",
		level: 1,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (10 ft ○)",
		components: "VS",
		duration: "Instant",
		school: "Conjuration",
		save: "Strength",
		damage: {
			value: "2d6",
			type: ["Necrotic"],
		},
		description:
			"<p>Invoking Hadar, you cause tendrils to erupt from yourself. Each creature in a 10-foot Emanation originating from you makes a Strength saving throw. On a failed save, a target takes 2d6 Necrotic damage and can’t take Reactions until the start of its next turn. On a successful save, a target takes half as much damage only.</p>",
		onHigherLevels:
			"Using a Higher-Level Spell Slot.</em></strong> The damage increases by 1d6 for each spell slot level above 1.",
		classes: ["Sorcerer", "Warlock"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_873,
		name: "Feign Death",
		level: 3,
		ritual: true,
		castingTime: "Action",
		range: "Touch",
		components: "VSM",
		duration: { value: 1, unit: "hour" },
		school: "Necromancy",
		description:
			"<p>You touch a willing creature and put it into a cataleptic state that is indistinguishable from death.</p><p>For the duration, the target appears dead to outward inspection and to spells used to determine the target’s status. The target has the Blinded and Incapacitated conditions, and its Speed is 0.</p><p>The target also has Resistance to all damage except Psychic damage, and it has Immunity to the Poisoned condition.",
		tags: ["Buff", "Debuff"],
		classes: ["Warlock", "Bard", "Cleric", "Druid", "Wizard"],
		source: "Player’s Handbook",
		material: "pinch of graveyard dirt",
	},
	{
		id: 2_618_888,
		name: "Aura of Purity",
		level: 4,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (30 ft ○)",
		components: "V",
		concentration: true,
		duration: { value: 10, unit: "minute" },
		school: "Abjuration",
		description:
			"<p>An aura radiates from you in a 30-foot Emanation for the duration. While in the aura, you and your allies have Resistance to Poison damage and Advantage on saving throws to avoid or end effects that include the Blinded, Charmed, Deafened, Frightened, Paralyzed, Poisoned, or Stunned condition.</p>",
		tags: ["Buff"],
		classes: ["Cleric", "Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_891,
		name: "Aura of Vitality",
		level: 3,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (30 ft ○)",
		components: "V",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Abjuration",
		description:
			"<p>An aura radiates from you in a 30-foot Emanation for the duration. When you create the aura and at the start of each of your turns while it persists, you can restore 2d6 Hit Points to one creature in it.</p>",
		tags: ["Healing"],
		classes: ["Cleric", "Druid", "Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_904,
		name: "Banishing Smite",
		level: 5,
		castingTime: "Bonus Action",
		range: "Self",
		components: "V",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Conjuration",
		save: "Charisma",
		damage: {
			value: "5d10",
			type: ["Force"],
		},
		description:
			"<p>The target hit by the attack roll takes an extra 5d10 Force damage from the attack. If the attack reduces the target to 50 Hit Points or fewer, the target must succeed on a Charisma saving throw or be transported to a harmless demiplane for the duration. While there, the target has the Incapacitated condition. When the spell ends, the target reappears in the space it left or in the nearest unoccupied space if that space is occupied.</p><p>Must be cast immediately after hitting a creature with a Melee weapon or an Unarmed Strike</p>",
		classes: ["Warlock", "Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_914,
		name: "Beast Sense",
		level: 2,
		ritual: true,
		castingTime: "Action",
		range: "Touch",
		components: "S",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Divination",
		description:
			"<p>You touch a willing Beast. For the duration, you can perceive through the Beast’s senses as well as your own. When perceiving through the Beast’s senses, you benefit from any special senses it has.</p>",
		classes: ["Druid", "Ranger"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_924,
		name: "Friends",
		level: 0,
		castingTime: "Action",
		range: { value: 10, unit: "ft" },
		components: "SM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Enchantment",
		description:
			"<p>You magically emanate a sense of friendship toward one creature you can see within range. The target must succeed on a Wisdom saving throw or have the Charmed condition for the duration. The target succeeds automatically if it isn’t a Humanoid, if you’re fighting it, or if you have cast this spell on it within the past 24 hours.</p><p>The spell ends early if the target takes damage or if you make an attack roll, deal damage, or force anyone to make a saving throw. When the spell ends, the target knows it was Charmed by you.</p>",
		tags: ["Buff"],
		classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "some makeup",
	},
	{
		id: 2_618_931,
		name: "Blade Ward",
		level: 0,
		castingTime: "Action",
		range: "Self",
		components: "VS",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Abjuration",
		description:
			"<p>Whenever a creature makes an attack roll against you before the spell ends, the attacker subtracts 1d4 from the attack roll.</p>",
		classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_936,
		name: "Blinding Smite",
		level: 3,
		castingTime: "Bonus Action",
		range: "Self",
		components: "V",
		duration: { value: 1, unit: "minute" },
		school: "Evocation",
		save: "Constitution",
		damage: {
			value: "3d8",
			type: ["Radiant"],
		},
		description:
			"<p>The target hit by the strike takes an extra 3d8 Radiant damage from the attack, and the target has the Blinded condition until the spell ends. At the end of each of its turns, the Blinded target makes a Constitution saving throw, ending the spell on itself on a success.</p>",
		onHigherLevels:
			"The extra damage increases by 1d8 for each spell slot level above 3.</p>><p>Must be cast immediately after hitting a creature with a Melee weapon or an Unarmed Strike",
		classes: ["Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_955,
		name: "Grasping Vine",
		level: 4,
		castingTime: "Bonus Action",
		range: { value: 60, unit: "ft" },
		components: "VS",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Conjuration",
		damage: {
			value: "4d8",
			type: ["Bludgeoning"],
		},
		description:
			"<p>You conjure a vine that sprouts from a surface in an unoccupied space that you can see within range. The vine lasts for the duration.</p><p>Make a melee spell attack against a creature within 30 feet of the vine. On a hit, the target takes 4d8 Bludgeoning damage and is pulled up to 30 feet toward the vine; if the target is Huge or smaller, it has the Grappled condition (escape DC equal to your spell save DC). The vine can grapple only one creature at a time, and you can cause the vine to release a Grappled creature (no action required).</p><p>As a Bonus Action on your later turns, you can repeat the attack against a creature within 30 feet of the vine.</p>",
		onHigherLevels:
			"The number of creatures the vine can grapple increases by one for each spell slot level above 4",
		classes: ["Cleric", "Druid", "Ranger"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_970,
		name: "Circle of Power",
		level: 5,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (30 ft ○)",
		components: "V",
		concentration: true,
		duration: { value: 10, unit: "minute" },
		school: "Abjuration",
		description:
			"<p>An aura radiates from you in a 30-foot Emanation for the duration. While in the aura, you and your allies have Advantage on saving throws against spells and other magical effects. When an affected creature makes a saving throw against a spell or magical effect that allows a save to take only half damage, it takes no damage if it succeeds on the save.</p>",
		tags: ["Buff"],
		classes: ["Cleric", "Paladin", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_974,
		name: "Cloud of Daggers",
		level: 2,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		aoeRange: "60 ft (5 ft □)",
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Conjuration",
		damage: {
			value: "4d4",
			type: ["Slashing"],
		},
		description:
			"<p>You conjure spinning daggers in a 5-foot Cube centered on a point within range. Each creature in that area takes 4d4 Slashing damage. A creature also takes this damage if it enters the Cube or ends its turn there or if the Cube moves into its space. A creature takes this damage only once per turn.</p><p>On your later turns, you can take a Magic action to teleport the Cube up to 30 feet.</p>",
		onHigherLevels: "The damage increases by 2d4 for each spell slot level above 2.",
		classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "sliver of glass",
	},
	{
		id: 2_618_975,
		name: "Hail of Thorns",
		level: 1,
		castingTime: "Bonus Action",
		range: "Self",
		components: "V",
		duration: "Instant",
		school: "Conjuration",
		save: "Dexterity",
		damage: {
			value: "1d10",
			type: ["Piercing"],
		},
		description:
			"<p>As you hit the creature, this spell creates a rain of thorns that sprouts from your Ranged weapon or ammunition. The target of the attack and each creature within 5 feet of it make a Dexterity saving throw, taking 1d10 Piercing damage on a failed save or half as much damage on a successful one.</p>",
		onHigherLevels:
			"The damage increases by 1d10 for each spell slot level above 1.</p><p>Must be cast immediately after hitting a creature with a Ranged weapon",
		classes: ["Ranger"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_990,
		name: "Compelled Duel",
		level: 1,
		castingTime: "Bonus Action",
		range: { value: 30, unit: "ft" },
		components: "V",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Enchantment",
		save: "Wisdom",
		description:
			"<p>You try to compel a creature into a duel. One creature that you can see within range makes a Wisdom saving throw. On a failed save, the target has Disadvantage on attack rolls against creatures other than you, and it can’t willingly move to a space that is more than 30 feet away from you.</p><p>The spell ends if you make an attack roll against a creature other than the target, if you cast a spell on an enemy other than the target, if an ally of yours damages the target, or if you end your turn more than 30 feet away from the target.</p>",
		tags: ["Debuff"],
		classes: ["Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_618_997,
		name: "Lightning Arrow",
		level: 3,
		castingTime: "Bonus Action",
		range: "Self",
		components: "VS",
		duration: "Instant",
		school: "Transmutation",
		save: "Dexterity",
		damage: {
			value: "2d8",
			type: ["Lightning"],
		},
		description:
			"<p>As your attack hits or misses the target, the weapon or ammunition you’re using transforms into a lightning bolt. Instead of taking any damage or other effects from the attack, the target takes 4d8 Lightning damage on a hit or half as much damage on a miss. Each creature within 10 feet of the target then makes a Dexterity saving throw, taking 2d8 Lightning damage on a failed save or half as much damage on a successful one.</p><p>The weapon or ammunition then returns to its normal form.</p><p>Must be cast immediately after hitting or missing a target with a ranged attack using a weapon</p>",
		onHigherLevels:
			"The damage for both effects of the spell increases by 1d8 for each spell slot level above 3.",
		classes: ["Ranger"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_037,
		name: "Mind Sliver",
		level: 0,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		components: "V",
		duration: { value: 1, unit: "round" },
		school: "Enchantment",
		save: "Intelligence",
		damage: {
			value: "1d6",
			type: ["Psychic"],
		},
		description:
			"<p>You try to temporarily sliver the mind of one creature you can see within range. The target must succeed on an Intelligence saving throw or take 1d6 Psychic damage and subtract 1d4 from the next saving throw it makes before the end of your next turn.</p>",
		onHigherLevels:
			"The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
		tags: ["Debuff"],
		classes: ["Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_038,
		name: "Mind Spike",
		level: 2,
		castingTime: "Action",
		range: { value: 120, unit: "ft" },
		components: "S",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Divination",
		save: "Wisdom",
		damage: {
			value: "3d8",
			type: ["Psychic"],
		},
		description:
			"<p>You drive a spike of psionic energy into the mind of one creature you can see within range. The target makes a Wisdom saving throw, taking 3d8 Psychic damage on a failed save or half as much damage on a successful one. On a failed save, you also always know the target’s location until the spell ends, but only while the two of you are on the same plane of existence. While you have this knowledge, the target can’t become hidden from you, and if it has the Invisible condition, it gains no benefit from that condition against you.</p>",
		onHigherLevels: "The damage increases by 1d8 for each spell slot level above 2.",
		classes: ["Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_045,
		name: "Conjure Barrage",
		level: 3,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (60 ft ▽)",
		components: "VSM",
		duration: "Instant",
		school: "Conjuration",
		save: "Dexterity",
		damage: {
			value: "5d8",
			type: ["Force"],
		},
		description:
			"<p>You brandish the weapon used to cast the spell and conjure similar spectral weapons (or ammunition appropriate to the weapon) that launch forward and then disappear. Each creature of your choice that you can see in a 60-foot Cone makes a Dexterity saving throw, taking 5d8 Force damage on a failed save or half as much damage on a successful one.</p>",
		onHigherLevels: "The damage increases by 1d8 for each spell slot level above 3.",
		classes: ["Ranger"],
		source: "Player’s Handbook",
		material: "Melee or Ranged weapon worth at least 1 CP",
	},
	{
		id: 2_619_050,
		name: "Conjure Volley",
		level: 5,
		castingTime: "Action",
		range: { value: 150, unit: "ft" },
		aoeRange: "150 ft (40 ft radius, 20 ft high ○)",
		components: "VSM",
		duration: "Instant",
		school: "Conjuration",
		save: "Dexterity",
		damage: {
			value: "8d8",
			type: ["Force"],
		},
		description:
			"<p>You brandish the weapon used to cast the spell and choose a point within range. Hundreds of similar spectral weapons (or ammunition appropriate to the weapon) fall in a volley and then disappear. Each creature of your choice that you can see in a 40-foot-radius, 20-foot-high Cylinder centered on that point makes a Dexterity saving throw. A creature takes 8d8 Force damage on a failed save or half as much damage on a successful one.</p>",
		classes: ["Ranger"],
		source: "Player’s Handbook",
		material: "Melee or Ranged weapon worth at least 1 CP",
	},
	{
		id: 2_619_055,
		name: "Cordon of Arrows",
		level: 2,
		castingTime: "Action",
		range: "Touch",
		components: "VSM",
		duration: { value: 8, unit: "hour" },
		school: "Transmutation",
		save: "Dexterity",
		damage: {
			value: "2d4",
			type: ["Piercing"],
		},
		description:
			"<p>You touch up to four nonmagical Arrows or Bolts and plant them in the ground in your space. Until the spell ends, the ammunition can’t be physically uprooted, and whenever a creature other than you enters a space within 30 feet of the ammunition for the first time on a turn or ends its turn there, one piece of ammunition flies up to strike it. The creature must succeed on a Dexterity saving throw or take 2d4 Piercing damage. The piece of ammunition is then destroyed. The spell ends when none of the ammunition remains planted in the ground.</p><p>When you cast this spell, you can designate any creatures you choose, and the spell ignores them.</p>",
		onHigherLevels:
			"The amount of ammunition that can be affected increases by two for each spell slot level above 2.",
		classes: ["Ranger"],
		source: "Player’s Handbook",
		material: "four or more arrows or bolts",
	},
	{
		id: 2_619_056,
		name: "Crown of Madness",
		level: 2,
		castingTime: "Action",
		range: { value: 120, unit: "ft" },
		components: "VS",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Enchantment",
		save: "Wisdom",
		description:
			"<p>One creature that you can see within range must succeed on a Wisdom saving throw or have the Charmed condition for the duration. The creature succeeds automatically if it isn’t Humanoid.</p><p>A spectral crown appears on the Charmed target's head, and it must use its action before moving on each of its turns to make a melee attack against a creature other than itself that you mentally choose. The target can act normally on its turn if you choose no creature or if no creature is within its reach. The target repeats the save at the end of each of its turns, ending the spell on itself on a success.</p><p>On your later turns, you must take the Magic action to maintain control of the target, or the spell ends.</p>",
		classes: ["Paladin", "Bard", "Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_057,
		name: "Crusader's Mantle",
		level: 3,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (30 ft ○)",
		components: "V",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Evocation",
		damage: {
			value: "1d4",
			type: ["Radiant"],
		},
		description:
			"<p>You radiate a magical aura in a 30-foot Emanation. While in the aura, you and your allies each deal an extra 1d4 Radiant damage when hitting with a weapon or an Unarmed Strike.</p>",
		tags: ["Buff"],
		classes: ["Cleric", "Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_084,
		name: "Staggering Smite",
		level: 4,
		castingTime: "Bonus Action",
		range: "Self",
		components: "V",
		duration: "Instant",
		school: "Enchantment",
		save: "Wisdom",
		damage: {
			value: "4d6",
			type: ["Psychic"],
		},
		description:
			"<p>The target takes an extra 4d6 Psychic damage from the attack, and the target must succeed on a Wisdom saving throw or have the Stunned condition until the end of your next turn.</p><p>Must be cast immediately after hitting a creature with a Melee weapon or an Unarmed Strike</p>",
		onHigherLevels: "The extra damage increases by 1d6 for each spell slot level above 4.",
		classes: ["Warlock", "Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_087,
		name: "Steel Wind Strike",
		level: 5,
		castingTime: "Action",
		range: { value: 30, unit: "ft" },
		components: "SM",
		duration: "Instant",
		school: "Conjuration",
		damage: {
			value: "6d10",
			type: ["Force"],
		},
		description:
			"<p>You flourish the weapon used in the casting and then vanish to strike like the wind. Choose up to five creatures you can see within range. Make a melee spell attack against each target. On a hit, a target takes 6d10 Force damage.</p><p>You then teleport to an unoccupied space you can see within 5 feet of one of the targets.</p>",
		tags: ["Teleportation"],
		classes: ["Cleric", "Ranger", "Wizard"],
		source: "Player’s Handbook",
		material: "Melee weapon worth 1+ SP",
	},
	{
		id: 2_619_089,
		name: "Destructive Wave",
		level: 5,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (30 ft ○)",
		components: "V",
		duration: "Instant",
		school: "Evocation",
		save: "Constitution",
		damage: {
			value: "5d6",
			type: ["Thunder", "Radiant", "Necrotic"],
		},
		description:
			"<p>Destructive energy ripples outward from you in a 30-foot Emanation. Each creature you choose in the Emanation makes a Constitution saving throw. On a failed save, a target takes 5d6 Thunder damage and 5d6 Radiant or Necrotic damage (your choice) and has the Prone condition. On a successful save, a target takes half as much damage only.</p>",
		classes: ["Cleric", "Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_105,
		name: "Summon Aberration",
		level: 4,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth an aberrant spirit. It manifests in an unoccupied space that you can see within range and uses the <strong>Aberrant Spirit</strong> stat block. When you cast the spell, choose Beholderkin, Mind Flayer, or Slaad. The creature resembles an Aberration of that kind, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, it shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="AberrantSpirit" class="compendium-hr">Aberrant Spirit</h4><p>Medium Aberration, Neutral</p><p><strong>AC</strong> 11 + the spell’s level</p><p><strong>HP</strong> 40 + 10 for each spell level above 4</p><p><strong>Speed</strong> 30 ft ; Fly 30 ft (hover; Beholderkin only)</p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>16</td><td>+3</td><td>+3</td></tr><tr><th>DEX</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>CON</th><td>15</td><td>+2</td><td>+2</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>16</td><td>+3</td><td>+3</td></tr><tr><th>WIS</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>CHA</th><td>6</td><td>−2</td><td>−2</td></tr></tbody></table></div><p><strong>Immunities</strong> Psychic</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 10</p><p><strong>Languages</strong> Deep Speech, understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Traits</p><p><strong><em>Regeneration (Slaad Only).</em></strong> The spirit regains 5 Hit Points at the start of its turn if it has at least 1 Hit Point.</p><p><strong><em>Whispering Aura (Mind Flayer Only).</em></strong> At the start of each of the spirit’s turns, the spirit emits psionic energy if it doesn’t have the Incapacitated condition. <em>Wisdom Saving Throw:</em> DC equals your spell save DC, each creature (other than you) within 5 feet of the spirit. <em>Failure:</em> 2d6 Psychic damage.</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of attacks equal to half this spell’s level (round down).</p><p><strong><em>Claw (Slaad Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d10 + 3 + the spell’s level Slashing damage, and the target can’t regain Hit Points until the start of the spirit’s next turn.</p><p><strong><em>Eye Ray (Beholderkin Only).</em></strong> <em>Ranged Attack Roll:</em> Bonus equals your spell attack modifier, range 150 ft <em>Hit:</em> 1d8 + 3 + the spell’s level Psychic damage.</p><p><strong><em>Psychic Slam (Mind Flayer Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:&nbsp;</em>1d8 + 3 + the spell’s level Psychic damage.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "pickled tentacle and an eyeball in a platinum-inlaid vial worth 400+ GP",
	},
	{
		id: 2_619_106,
		name: "Summon Beast",
		level: 2,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth a bestial spirit. It manifests in an unoccupied space that you can see within range and uses the <strong>Bestial Spirit</strong> stat block. When you cast the spell, choose an environment: Air, Land, or Water. The creature resembles an animal of your choice that is native to the chosen environment, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="BestialSpirit" class="compendium-hr">Bestial Spirit</h4><p>Small Beast, Neutral</p><p><strong>AC</strong> 11 + the spell’s level</p><p><strong>HP</strong> 20 (Air only) or 30 (Land and Water only) + 5 for each spell level above 2</p><p><strong>Speed</strong> 30 ft ; Climb 30 ft (Land only); Fly 60 ft (Air only); Swim 30 ft (Water only)</p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>18</td><td>+4</td><td>+4</td></tr><tr><th>DEX</th><td>11</td><td>+0</td><td>+0</td></tr><tr><th>CON</th><td>16</td><td>+3</td><td>+3</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>4</td><td>–3</td><td>–3</td></tr><tr><th>WIS</th><td>14</td><td>+2</td><td>+2</td></tr><tr><th>CHA</th><td>5</td><td>−3</td><td>−3</td></tr></tbody></table></div><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 12</p><p><strong>Languages</strong> understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Traits</p><p><strong><em>Flyby (Air Only).</em></strong> The spirit doesn’t provoke Opportunity Attacks when it flies out of an enemy’s reach.</p><p><strong><em>Pack Tactics (Land and Water Only).</em></strong> The spirit has Advantage on an attack roll against a creature if at least one of the spirit’s allies is within 5 feet of the creature and the ally doesn’t have the Incapacitated condition.</p><p><strong><em>Water Breathing (Water Only).</em></strong> The spirit can breathe only underwater.</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of Rend attacks equal to half this spell’s level (round down).</p><p><strong><em>Rend.</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d8 + 4 + the spell’s level Piercing damage.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Druid", "Ranger"],
		source: "Player’s Handbook",
		material: "feather, tuft of fur, and fish tail inside a gilded acorn worth 200+ GP",
	},
	{
		id: 2_619_108,
		name: "Summon Celestial",
		level: 5,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth a Celestial spirit. It manifests in an angelic form in an unoccupied space that you can see within range and uses the <strong>Celestial Spirit</strong> stat block. When you cast the spell, choose Avenger or Defender. Your choice determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="CelestialSpirit" class="compendium-hr">Celestial Spirit</h4><p>Large Celestial, Neutral</p><p><strong>AC</strong> 11 + the spell’s level + 2 (Defender only)</p><p><strong>HP</strong> 40 + 10 for each spell level above 5</p><p><strong>Speed</strong> 30 ft , Fly 40 ft </p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>16</td><td>+3</td><td>+3</td></tr><tr><th>DEX</th><td>14</td><td>+2</td><td>+2</td></tr><tr><th>CON</th><td>16</td><td>+3</td><td>+3</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>WIS</th><td>14</td><td>+2</td><td>+2</td></tr><tr><th>CHA</th><td>16</td><td>+3</td><td>+3</td></tr></tbody></table></div><p><strong>Resistances</strong> Radiant</p><p><strong>Immunities</strong> Charmed, Frightened</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 12</p><p><strong>Languages</strong> Celestial, understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of attacks equal to half this spell’s level (round down).</p><p><strong><em>Radiant Bow (Avenger Only).</em></strong> <em>Ranged Attack Roll</em>: Bonus equals your spell attack modifier, range 600 ft <em>Hit:</em> 2d6 + 2 + the spell’s level Radiant damage.</p><p><strong><em>Radiant Mace (Defender Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d10 + 3 + the spell’s level Radiant damage, and the spirit can choose itself or another creature it can see within 10 feet of the target. The chosen creature gains 1d10 Temporary Hit Points.</p><p><strong><em>Healing Touch (1/Day).</em></strong> The spirit touches another creature. The target regains Hit Points equal to 2d8 + the spell’s level.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Warlock", "Cleric", "Paladin"],
		source: "Player’s Handbook",
		material: "reliquary worth 500+ GP",
	},
	{
		id: 2_619_111,
		name: "Summon Construct",
		level: 4,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth the spirit of a Construct. It manifests in an unoccupied space that you can see within range and uses the <strong>Construct Spirit</strong> stat block. When you cast the spell, choose a material: Clay, Metal, or Stone. The creature resembles an animate statue (you determine the appearance) made of the chosen material, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="ConstructSpirit" class="compendium-hr">Construct Spirit</h4><p>Medium Construct, Neutral</p><p><strong>AC</strong> 13 + the spell’s level</p><p><strong>HP</strong> 40 + 15 for each spell level above 4</p><p><strong>Speed</strong> 30 ft </p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>18</td><td>+4</td><td>+4</td></tr><tr><th>DEX</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>CON</th><td>18</td><td>+4</td><td>+4</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>14</td><td>+2</td><td>+2</td></tr><tr><th>WIS</th><td>11</td><td>+0</td><td>+0</td></tr><tr><th>CHA</th><td>5</td><td>−3</td><td>−3</td></tr></tbody></table></div><p><strong>Resistances</strong> Poison</p><p><strong>Immunities</strong> Charmed, Exhaustion, Frightened, Paralyzed, Poisoned</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 10</p><p><strong>Languages</strong> Understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Traits</p><p><strong><em>Heated Body (Metal Only).</em></strong> A creature that hits the spirit with a melee attack or that starts its turn in a grapple with the spirit takes 1d10 Fire damage.</p><p><strong><em>Stony Lethargy (Stone Only).</em></strong> When a creature starts its turn within 10 feet of the spirit, the spirit can target it with magical energy if the spirit can see it. <em>Wisdom Saving Throw:</em> DC equals your spell save DC, the target. <em>Failure:</em> Until the start of its next turn, the target can’t make Opportunity Attacks, and its Speed is halved.</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of Slam attacks equal to half this spell’s level (round down).</p><p><strong><em>Slam.</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d8 + 4 + the spell’s level Bludgeoning damage.</p><p class="monster-header">Reactions</p><p><strong><em>Berserk Lashing (Clay Only).</em></strong> <em>Trigger:</em> The spirit takes damage from a creature. <em>Response:</em> The spirit makes a Slam attack against that creature if possible, or the spirit moves up to half its Speed toward that creature without provoking Opportunity Attacks.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Sorcerer", "Wizard"],
		source: "Player’s Handbook",
		material: "lockbox worth 400+ GP",
	},
	{
		id: 2_619_113,
		name: "Summon Elemental",
		level: 4,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth an Elemental spirit. It manifests in an unoccupied space that you can see within range and uses the <strong>Elemental Spirit</strong> stat block. When you cast the spell, choose an element: Air, Earth, Fire, or Water. The creature resembles a bipedal form wreathed in the chosen element, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="ElementalSpirit" class="compendium-hr">Elemental Spirit</h4><p>Medium Elemental, Neutral</p><p><strong>AC</strong> 11 + the spell’s level</p><p><strong>HP</strong> 50 + 10 for each spell level above 4</p><p><strong>Speed</strong> 40 ft ; Burrow 40 ft (Earth only); Fly 40 ft (hover; Air only); Swim 40 ft (Water only)</p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>18</td><td>+4</td><td>+4</td></tr><tr><th>DEX</th><td>15</td><td>+2</td><td>+2</td></tr><tr><th>CON</th><td>17</td><td>+3</td><td>+3</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>4</td><td>–3</td><td>–3</td></tr><tr><th>WIS</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>CHA</th><td>16</td><td>+3</td><td>+3</td></tr></tbody></table></div><p><strong>Resistances</strong> Acid (Water only), Lightning and Thunder (Air only), Piercing and Slashing (Earth only)</p><p><strong>Immunities</strong> Fire (Fire only), Poison; Exhaustion, Paralyzed, Petrified, Poisoned</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 10</p><p><strong>Languages</strong> Primordial, understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Traits</p><p><strong><em>Amorphous Form (Air, Fire, and Water Only).</em></strong> The spirit can move through a space as narrow as 1 inch wide without it counting as Difficult Terrain.</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of Slam attacks equal to half this spell’s level (round down).</p><p><strong><em>Slam.</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d10 + 4 + the spell’s level Bludgeoning (Earth only), Cold (Water only), Lightning (Air only), or Fire (Fire only) damage.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Warlock", "Druid", "Ranger", "Wizard"],
		source: "Player’s Handbook",
		material: "air, a pebble, ash, and water inside a gold-inlaid vial worth 400+ GP",
	},
	{
		id: 2_619_115,
		name: "Summon Fey",
		level: 3,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth a Fey spirit. It manifests in an unoccupied space that you can see within range and uses the <strong>Fey Spirit</strong> stat block. When you cast the spell, choose a mood: Fuming, Mirthful, or Tricksy. The creature resembles a Fey creature of your choice marked by the chosen mood, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="FeySpirit" class="compendium-hr">Fey Spirit</h4><p>Small Fey, Neutral</p><p><strong>AC</strong> 12 + the spell’s level</p><p><strong>HP</strong> 30 + 10 for each spell level above 3</p><p><strong>Speed</strong> 30 ft , Fly 30 ft </p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>13</td><td>+1</td><td>+1</td></tr><tr><th>DEX</th><td>16</td><td>+3</td><td>+3</td></tr><tr><th>CON</th><td>14</td><td>+2</td><td>+2</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>14</td><td>+2</td><td>+2</td></tr><tr><th>WIS</th><td>11</td><td>+0</td><td>+0</td></tr><tr><th>CHA</th><td>16</td><td>+3</td><td>+3</td></tr></tbody></table></div><p><strong>Immunities</strong> Charmed</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 10</p><p><strong>Languages</strong> Sylvan, understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of Fey Blade attacks equal to half this spell’s level (round down).</p><p><strong><em>Fey Blade.</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 2d6 + 3 + the spell’s level Force damage.</p><p class="monster-header">Bonus Actions</p><p><strong><em>Fey Step.</em></strong> The spirit magically teleports up to 30 feet to an unoccupied space it can see. Then one of the following effects occurs, based on the spirit’s chosen mood:</p><p><strong>Fuming.</strong> The spirit has Advantage on the next attack roll it makes before the end of this turn.</p><p><strong>Mirthful.</strong> <em>Wisdom Saving Throw:</em> DC equals your spell save DC, one creature the spirit can see within 10 feet of itself. <em>Failure:</em> The target is Charmed by you and the spirit for 1 minute or until the target takes any damage.</p><p><strong>Tricksy.</strong> The spirit fills a 10-foot Cube within 5 feet of it with magical Darkness, which lasts until the end of its next turn.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Ranger", "Druid", "Ranger", "Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "gilded flower worth 300+ GP",
	},
	{
		id: 2_619_117,
		name: "Summon Fiend",
		level: 6,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Conjuration",
		description:
			'<p>You call forth a fiendish spirit. It manifests in an unoccupied space that you can see within range and uses the <strong>Fiendish Spirit</strong> stat block. When you cast the spell, choose Demon, Devil, or Yugoloth. The creature resembles a Fiend of the chosen type, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="FiendishSpirit" class="compendium-hr">Fiendish Spirit</h4><p>Large Fiend, Neutral</p><p><strong>AC</strong> 12 + the spell’s level</p><p><strong>HP</strong> 50 (Demon only) or 40 (Devil only) or 60 (Yugoloth only) + 15 for each spell level above 6</p><p><strong>Speed</strong> 40 ft ; Climb 40 ft (Demon only); Fly 60 ft (Devil only)</p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>13</td><td>+1</td><td>+1</td></tr><tr><th>DEX</th><td>16</td><td>+3</td><td>+3</td></tr><tr><th>CON</th><td>15</td><td>+2</td><td>+2</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>WIS</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>CHA</th><td>16</td><td>+3</td><td>+3</td></tr></tbody></table></div><p><strong>Resistances</strong> Fire</p><p><strong>Immunities</strong> Poison; Poisoned</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 10</p><p><strong>Languages</strong> Abyssal, Infernal, Telepathy 60 ft </p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Traits</p><p><strong><em>Death Throes (Demon Only).</em></strong> When the spirit drops to 0 Hit Points or the spell ends, the spirit explodes. <em>Dexterity Saving Throw:</em> DC equals your spell save DC, each creature in a 10-foot Emanation originating from the spirit. <em>Failure:</em> 2d10 plus this spell’s level Fire damage. <em>Success:</em> Half damage.</p><p><strong><em>Devil’s Sight (Devil Only).</em></strong> Magical Darkness doesn’t impede the spirit’s Darkvision.</p><p><strong><em>Magic Resistance.</em></strong> The spirit has Advantage on saving throws against spells and other magical eff ects.</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of attacks equal to half this spell’s level (round down).</p><p><strong><em>Bite (Demon Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d12 + 3 + the spell’s level Necrotic damage.</p><p><strong><em>Claws (Yugoloth Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d8 + 3 + the spell’s level Slashing damage. Immediately after the attack hits or misses, the spirit can teleport up to 30 feet to an unoccupied space it can see.</p><p><strong><em>Fiery Strike (Devil Only).</em></strong> <em>Melee or Ranged Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft or range 150 ft <em>Hit:</em> 2d6 + 3 + the spell’s level Fire damage.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "bloody vial worth 600+ GP",
	},
	{
		id: 2_619_119,
		name: "Summon Undead",
		level: 3,
		castingTime: "Action",
		range: { value: 90, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Necromancy",
		description:
			'<p>You call forth an Undead spirit. It manifests in an unoccupied space that you can see within range and uses the <strong>Undead Spirit</strong> stat block. When you cast the spell, choose the creature’s form: Ghostly, Putrid, or Skeletal. The spirit resembles an Undead creature with the chosen form, which determines certain details in its stat block. The creature disappears when it drops to 0 Hit Points or when the spell ends.</p><p>The creature is an ally to you and your allies. In combat, the creature shares your Initiative count, but it takes its turn immediately after yours. It obeys your verbal commands (no action required by you). If you don’t issue any, it takes the Dodge action and uses its movement to avoid danger.</p><div class="stat-block"><h4 id="UndeadSpirit" class="compendium-hr">Undead Spirit</h4><p>Medium Undead, Neutral</p><p><strong>AC</strong> 11 + the spell’s level</p><p><strong>HP</strong> 30 (Ghostly and Putrid only) or 20 (Skeletal only) + 10 for each spell level above 3</p><p><strong>Speed</strong> 30 ft ; Fly 40 ft (hover; Ghostly only)</p><div class="stats"><table class="physical abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>STR</th><td>12</td><td>+1</td><td>+1</td></tr><tr><th>DEX</th><td>16</td><td>+3</td><td>+3</td></tr><tr><th>CON</th><td>15</td><td>+2</td><td>+2</td></tr></tbody></table><table class="mental abilities-saves"><thead><tr><th>&nbsp;</th><th>&nbsp;</th><th>Mod</th><th>Save</th></tr></thead><tbody><tr><th>INT</th><td>4</td><td>−3</td><td>−3</td></tr><tr><th>WIS</th><td>10</td><td>+0</td><td>+0</td></tr><tr><th>CHA</th><td>9</td><td>−1</td><td>−1</td></tr></tbody></table></div><p><strong>Immunities</strong> Necrotic, Poison; Exhaustion, Frightened, Paralyzed, Poisoned</p><p><strong>Senses</strong> Darkvision 60 ft , Passive Perception 10</p><p><strong>Languages</strong> Understands the languages you know</p><p><strong>CR</strong> None (XP 0; PB equals your Proficiency Bonus)</p><p class="monster-header">Traits</p><p><strong><em>Festering Aura (Putrid Only).</em></strong> <em>Constitution Saving Throw:</em> DC equals your spell save DC, any creature (other than you) that starts its turn within a 5-foot Emanation originating from the spirit. <em>Failure:</em> The creature has the Poisoned condition until the start of its next turn.</p><p><strong><em>Incorporeal Passage (Ghostly Only).</em></strong> The spirit can move through other creatures and objects as if they were Difficult Terrain. If it ends its turn inside an object, it is shunted to the nearest unoccupied space and takes 1d10 Force damage for every 5 feet traveled.</p><p class="monster-header">Actions</p><p><strong><em>Multiattack.</em></strong> The spirit makes a number of attacks equal to half this spell’s level (round down).</p><p><strong><em>Deathly Touch (Ghostly Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d8 + 3 + the spell’s level Necrotic damage, and the target has the Frightened condition until the end of its next turn.</p><p><strong><em>Grave Bolt (Skeletal Only).</em></strong> <em>Ranged Attack Roll:</em> Bonus equals your spell attack modifier, range 150 ft <em>Hit:</em> 2d4 + 3 + the spell’s level Necrotic damage.</p><p><strong><em>Rotting Claw (Putrid Only).</em></strong> <em>Melee Attack Roll:</em> Bonus equals your spell attack modifier, reach 5 ft <em>Hit:</em> 1d6 + 3 + the spell’s level Slashing damage. If the target has the Poisoned condition, it has the Paralyzed condition until the end of its next turn.</p></div>',
		onHigherLevels: "Use the spell slot’s level for the spell’s level in the stat block.",
		tags: ["Minions"],
		classes: ["Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "gilded skull worth 300+ GP",
	},
	{
		id: 2_619_125,
		name: "Swift Quiver",
		level: 5,
		castingTime: "Bonus Action",
		range: "Self",
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Transmutation",
		description:
			"<p>When you cast the spell and as a Bonus Action until it ends, you can make two attacks with a weapon that fires Arrows or Bolts, such as a Longbow or a Light Crossbow. The spell magically creates the ammunition needed for each attack. Each Arrow or Bolt created by the spell deals damage like a nonmagical piece of ammunition of its kind and disintegrates immediately after it hits or misses.</p>",
		tags: ["Buff"],
		classes: ["Ranger"],
		source: "Player’s Handbook",
		material: "quiver worth 1+ GP",
	},
	{
		id: 2_619_129,
		name: "Synaptic Static",
		level: 5,
		castingTime: "Action",
		range: { value: 120, unit: "ft" },
		aoeRange: "120 ft (20 ft ○)",
		components: "VS",
		duration: "Instant",
		school: "Enchantment",
		save: "Intelligence",
		damage: {
			value: "8d6",
			type: ["Psychic"],
		},
		description:
			"<p>You cause psychic energy to erupt at a point within range. Each creature in a 20-foot-radius Sphere centered on that point makes an Intelligence saving throw, taking 8d6 Psychic damage on a failed save or half as much damage on a successful one.</p><p>On a failed save, a target also has muddled thoughts for 1 minute. During that time, it subtracts 1d6 from all its attack rolls and ability checks, as well as any Constitution saving throws to maintain Concentration. The target makes an Intelligence saving throw at the end of each of its turns, ending the effect on itself on a success.</p>",
		tags: ["Debuff"],
		classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_159,
		name: "Telepathy",
		level: 8,
		castingTime: "Action",
		range: "Unlimited",
		components: "VSM",
		duration: { value: 24, unit: "hour" },
		school: "Divination",
		description:
			"<p>You create a telepathic link between yourself and a willing creature with which you are familiar. The creature can be anywhere on the same plane of existence as you. The spell ends if you or the target are no longer on the same plane.</p><p>Until the spell ends, you and the target can instantly share words, images, sounds, and other sensory messages with each other through the link, and the target recognizes you as the creature it is communicating with. The spell enables a creature to understand the meaning of your words and any sensory messages you send to it.</p>",
		classes: ["Wizard"],
		source: "Player’s Handbook",
		material: "pair of linked silver rings",
	},
	{
		id: 2_619_162,
		name: "Hunger of Hadar",
		level: 3,
		castingTime: "Action",
		range: { value: 150, unit: "ft" },
		aoeRange: "150 ft (20 ft ○)",
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Conjuration",
		save: "Dexterity",
		damage: {
			value: "4d6",
			type: ["Cold", "Acid"],
		},
		description:
			"<p>You open a gateway to the Far Realm, a region infested with unspeakable horrors. A 20-foot-radius Sphere of Darkness appears, centered on a point with range and lasting for the duration. The Sphere is Difficult Terrain, and it is filled with strange whispers and slurping noises, which can be heard up to 30 feet away. No light, magical or otherwise, can illuminate the area, and creatures fully within it have the Blinded condition.</p><p>Any creature that starts its turn in the area takes 2d6 Cold damage. Any creature that ends its turn there must succeed on a Dexterity saving throw or take 2d6 Acid damage from otherworldly tentacles.</p>",
		onHigherLevels:
			"The Cold or Acid damage (your choice) increases by 1d6 for each spell slot level above 3.",
		classes: ["Sorcerer", "Warlock"],
		source: "Player’s Handbook",
		material: "pickled tentacle",
	},
	{
		id: 2_619_164,
		name: "Elemental Weapon",
		level: 3,
		castingTime: "Action",
		range: "Touch",
		components: "VS",
		concentration: true,
		duration: { value: 1, unit: "hour" },
		school: "Transmutation",
		damage: {
			value: "1d4",
			type: ["Acid", "Cold", "Fire", "Lightning", "Thunder"],
		},
		description:
			"<p>A nonmagical weapon you touch becomes a magic weapon. Choose one of the following damage types: Acid, Cold, Fire, Lightning, or Thunder. For the duration, the weapon has a +1 bonus to attack rolls and deals an extra 1d4 damage of the chosen type when it hits.</p>",
		onHigherLevels:
			"If you use a level 5–6 spell slot, the bonus to attack rolls increases to +2, and the extra damage increases to 2d4. If you use a level 7+ spell slot, the bonus increases to +3, and the extra damage increases to 3d4.",
		tags: ["Buff"],
		classes: ["Cleric", "Warlock", "Druid", "Paladin", "Ranger"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_171,
		name: "Ice Knife",
		level: 1,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		aoeRange: "60 ft (5 ft)",
		components: "SM",
		duration: "Instant",
		school: "Conjuration",
		save: "Dexterity",
		damage: {
			value: "1d10",
			type: ["Piercing", "Cold"],
		},
		description:
			"<p>You create a shard of ice and fling it at one creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 Piercing damage. Hit or miss, the shard then explodes. The target and each creature within 5 feet of it must succeed on a Dexterity saving throw or take 2d6 Cold damage.</p>",
		onHigherLevels: "The Cold damage increases by 1d6 for each spell slot level above 1.",
		classes: ["Druid", "Sorcerer", "Wizard"],
		source: "Player’s Handbook",
		material: "drop of water or a piece of ice",
	},
	{
		id: 2_619_176,
		name: "Thorn Whip",
		level: 0,
		castingTime: "Action",
		range: { value: 30, unit: "ft" },
		components: "VSM",
		duration: "Instant",
		school: "Transmutation",
		damage: {
			value: "1d6",
			type: ["Piercing"],
		},
		description:
			"<p>You create a vine-like whip covered in thorns that lashes out at your command toward a creature in range. Make a melee spell attack against the target. On a hit, the target takes 1d6 Piercing damage, and if it is Large or smaller, you can pull it up to 10 feet closer to you.</p>",
		onHigherLevels:
			"The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
		classes: ["Druid"],
		source: "Player’s Handbook",
		material: "stem of a plant with thorns",
	},
	{
		id: 2_619_179,
		name: "Thunderclap",
		level: 0,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (5 ft ○)",
		components: "S",
		duration: "Instant",
		school: "Evocation",
		save: "Constitution",
		damage: {
			value: "1d6",
			type: ["Thunder"],
		},
		description:
			"<p>Each creature in a 5-foot Emanation originating from you must succeed on a Constitution saving throw or take 1d6 Thunder damage. The spell’s thunderous sound can be heard up to 100 feet away.</p>",
		onHigherLevels:
			"The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
		classes: ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_182,
		name: "Thunderous Smite",
		level: 1,
		castingTime: "Bonus Action",
		range: "Self",
		components: "V",
		duration: "Instant",
		school: "Evocation",
		save: "Strength",
		damage: {
			value: "2d6",
			type: ["Thunder"],
		},
		description:
			"<p>Your strike rings with thunder that is audible within 300 feet of you, and the target takes an extra 2d6 Thunder damage from the attack. Additionally, if the target is a creature, it must succeed on a Strength saving throw or be pushed 10 feet away from you and have the Prone condition.</p><p>Must be cast immediately after hitting a target with a Melee weapon or an Unarmed Strike</p>",
		onHigherLevels: "The damage increases by 1d6 for each spell slot level above 1.",
		classes: ["Paladin"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_188,
		name: "Toll the Dead",
		level: 0,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		components: "VS",
		duration: "Instant",
		school: "Necromancy",
		save: "Wisdom",
		damage: {
			value: "1d8",
			type: ["Necrotic"],
		},
		description:
			"<p>You point at one creature you can see within range, and the single chime of a dolorous bell is audible within 10 feet of the target. The target must succeed on a Wisdom saving throw or take 1d8 Necrotic damage. If the target is missing any of its Hit Points, it instead takes 1d12 Necrotic damage.</p>",
		onHigherLevels:
			"The damage increases by one die when you reach levels 5 (2d8 or 2d12), 11 (3d8 or 3d12), and 17 (4d8 or 4d12).",
		classes: ["Cleric", "Warlock", "Wizard"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_206,
		name: "Tsunami",
		level: 8,
		castingTime: { value: 1, unit: "minute" },
		range: { value: 1, unit: "miles" },
		components: "VS",
		concentration: true,
		duration: { value: 6, unit: "round" },
		school: "Conjuration",
		save: "Strength",
		damage: {
			value: "6d10",
			type: ["Bludgeoning"],
		},
		description:
			"<p>A wall of water springs into existence at a point you choose within range. You can make the wall up to 300 feet long, 300 feet high, and 50 feet thick. The wall lasts for the duration.</p><p>When the wall appears, each creature in its area makes a Strength saving throw, taking 6d10 Bludgeoning damage on a failed save or half as much damage on a successful one.</p><p>At the start of each of your turns after the wall appears, the wall, along with any creatures in it, moves 50 feet away from you. Any Huge or smaller creature inside the wall or whose space the wall enters when it moves must succeed on a Strength saving throw or take 5d10 Bludgeoning damage. A creature can take this damage only once per round. At the end of the turn, the wall’s height is reduced by 50 feet, and the damage the wall deals on later rounds is reduced by 1d10. When the wall reaches 0 feet in height, the spell ends.</p><p>A creature caught in the wall can move by swimming. Because of the wave’s force, though, the creature must succeed on a Strength (Athletics) check against your spell save DC to move at all. If it fails the check, it can’t move. A creature that moves out of the wall falls to the ground.</p>",
		classes: ["Druid"],
		source: "Player’s Handbook",
	},
	{
		id: 2_619_215,
		name: "Witch Bolt",
		level: 1,
		castingTime: "Action",
		range: { value: 60, unit: "ft" },
		components: "VSM",
		concentration: true,
		duration: { value: 1, unit: "minute" },
		school: "Evocation",
		damage: {
			value: "2d12",
			type: ["Lightning"],
		},
		description:
			"<p>A beam of crackling energy lances toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against it. On a hit, the target takes 2d12 Lightning damage.</p><p>On each of your subsequent turns, you can take a Bonus Action to deal 1d12 Lightning damage to the target automatically, even if the first attack missed.</p><p>The spell ends if the target is ever outside the spell’s range or if it has Total Cover from you.</p>",
		onHigherLevels: "The initial damage increases by 1d12 for each spell slot level above 1.",
		classes: ["Sorcerer", "Warlock", "Wizard"],
		source: "Player’s Handbook",
		material: "twig struck by lightning",
	},
	{
		id: 2_619_217,
		name: "Word of Radiance",
		level: 0,
		castingTime: "Action",
		range: "Self",
		aoeRange: "Self (5 ft ○)",
		components: "VM",
		duration: "Instant",
		school: "Evocation",
		save: "Constitution",
		damage: {
			value: "1d6",
			type: ["Radiant"],
		},
		description:
			"<p>Burning radiance erupts from you in a 5-foot Emanation. Each creature of your choice that you can see in it must succeed on a Constitution saving throw or take 1d6 Radiant damage.</p>",
		onHigherLevels:
			"The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
		classes: ["Cleric"],
		source: "Player’s Handbook",
		material: "sunburst token",
	},
	{
		id: 2_619_219,
		name: "Vitriolic Sphere",
		level: 4,
		castingTime: "Action",
		range: { value: 150, unit: "ft" },
		aoeRange: "150 ft (20 ft ○)",
		components: "VSM",
		duration: "Instant",
		school: "Evocation",
		save: "Dexterity",
		damage: {
			value: "10d4",
			type: ["Acid"],
		},
		description:
			"<p>You point at a location within range, and a glowing, 1-foot-diameter ball of acid streaks there and explodes in a 20-foot-radius Sphere. Each creature in that area makes a Dexterity saving throw. On a failed save, a creature takes 10d4 Acid damage and another 5d4 Acid damage at the end of its next turn. On a successful save, a creature takes half the initial damage only.</p>",
		onHigherLevels: "The initial damage increases by 2d4 for each spell slot level above 4.",
		classes: ["Sorcerer", "Wizard"],
		source: "Player’s Handbook",
		material: "drop bile",
	},
	{
		id: 2_619_220,
		name: "Wrathful Smite",
		level: 1,
		castingTime: "Bonus Action",
		range: "Self",
		components: "V",
		duration: { value: 1, unit: "minute" },
		school: "Necromancy",
		save: "Wisdom",
		damage: {
			value: "1d6",
			type: ["Necrotic"],
		},
		description:
			"<p>The target takes an extra 1d6 Necrotic damage from the attack, and it must succeed on a Wisdom saving throw or have the Frightened condition until the spell ends. At the end of each of its turns, the Frightened target repeats the save, ending the spell on itself on a success.</p><p>Must be cast immediately after hitting a creature with a Melee weapon or an Unarmed Strike</p>",
		onHigherLevels: "The damage increases by 1d6 for each spell slot level above 1.",
		classes: ["Warlock", "Paladin"],
		source: "Player’s Handbook",
	},
];
